spring.application.name=dbprak7

spring.datasource.url=jdbc:postgresql://localhost:5432/mediastore
spring.datasource.username=postgres
spring.datasource.password=guest

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#folgende Zeilen kann man theoretisch weglassen weil sie automatisch bestimmt werden
#in SWTP hatte wir sie aber drin, also würde ich sie einkommentieren wenn wir fehler kriegen

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
