spring.application.name=backendDBP
spring.datasource.url=jdbc:postgresql://localhost:5432/mediastore
spring.datasource.username=postgres
spring.datasource.password=guest
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
whitelisted.cors.urls=http://localhost:5173, http://localhost:5174, http://localhost:5175